### ISSUE TITLE
Cannot import name 'TEMP_CELSIUS' from 'homeassistant.components.climate'

### ISSUE THREAD

**Issue by Aerodynamite** [joleys/niko-home-control-II#47]
Hi,

The NHC2 integration stopped working after upgrading HA to 2023.1.1. On startup I receive the follow error log:

```
Logger: homeassistant.setup
Source: setup.py:210
First occurred: 11:33:35 AM (1 occurrences)
Last logged: 11:33:35 AM

Setup failed for custom integration nhc2: Unable to import component: cannot import name 'TEMP_CELSIUS' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)
```

Any ideas how to fix this?

**Comment by MirandaPoth** [comment]
Do you have the latest version? This import was removed a few weeks ago.

**Comment by Aerodynamite** [comment]
My bad, I forgot I manually installed the nhc2 custom_component many months ago before I started using HACS and forgot this was not a built-in integration!

Installing/updating this integration through HACS fixed the issue. Thank you for the help!
