### ISSUE TITLE
Niko Home control II not working after update to HA 2024.5.5

### ISSUE THREAD

**Issue by Jimnaldo** [joleys/niko-home-control-II#149]
After update to 2024.5.5 no connection between niko home control II and HA please advise?

**Comment by tijsverkoyen** [comment]
Anything in the logs?

**Comment by Jimnaldo** [comment]
I didn't check unfortunately and i'm back at a previous version of HA

**Comment by vgillebert** [comment]
Here are my logs:
2024-05-30 21:21:19.248 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.nhc2',) in /usr/src/homeassistant/homeassistant/loader.py, line 1046: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop
2024-05-30 21:21:20.010 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'value_json' is undefined when rendering '{{value_json}}'
2024-05-30 21:21:20.004 ERROR (Thread-5 (_thread_main)) [custom_components.nhc2.nhccoco.coco] 'NoneType' object has no attribute 'loop'
Traceback (most recent call last):
File "/config/custom_components/nhc2/nhccoco/coco.py", line 161, in _on_message
self._device_instances[device[MQTT_DATA_PARAMS_DEVICES_UUID]].on_change(topic, device)
File "/config/custom_components/nhc2/nhccoco/devices/electricity_clamp_centralmeter.py", line 60, in on_change
callback()
File "/config/custom_components/nhc2/entities/electricity_clamp_centralmeter_report_instant_usage.py", line 50, in on_change
self.schedule_update_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1235, in schedule_update_ha_state
self.hass.loop.call_soon_threadsafe(

Thank you for your help

**Comment by joleys** [comment]
I'm at 2024.5.5 without any big issue.

**Comment by vgillebert** [comment]
> I'm at 2024.5.5 without any big issue.

It was back the 31/5 around 2pm. I don't know how, why.

**Comment by steffendm** [comment]
> Here are my logs: 2024-05-30 21:21:19.248 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.nhc2',) in /usr/src/homeassistant/homeassistant/loader.py, line 1046: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop 2024-05-30 21:21:20.010 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'value_json' is undefined when rendering '{{value_json}}' 2024-05-30 21:21:20.004 ERROR (Thread-5 (_thread_main)) [custom_components.nhc2.nhccoco.coco] 'NoneType' object has no attribute 'loop' Traceback (most recent call last): File "/config/custom_components/nhc2/nhccoco/coco.py", line 161, in _on_message self._device_instances[device[MQTT_DATA_PARAMS_DEVICES_UUID]].on_change(topic, device) File "/config/custom_components/nhc2/nhccoco/devices/electricity_clamp_centralmeter.py", line 60, in on_change callback() File "/config/custom_components/nhc2/entities/electricity_clamp_centralmeter_report_instant_usage.py", line 50, in on_change self.schedule_update_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1235, in schedule_update_ha_state self.hass.loop.call_soon_threadsafe(
> 
> Thank you for your help

I have the same error...
Core is at 2024.5.5

**Comment by tijsverkoyen** [comment]
I am running 2024.5.5 without any problems here.
@steffendm still an issue?

**Comment by CasperNaudts** [comment]
Hi @tijsverkoyen, I'm having issue with the live power consumption since HA 2024.5.5 but could also be related to the Niko system update that got installed at roughly the same moment. All other features seam to work.

**Comment by tijsverkoyen** [comment]
> Hi @tijsverkoyen, I'm having issue with the live power consumption since HA 2024.5.5 but could also be related to the Niko system update that got installed at roughly the same moment. All other features seam to work.

Can you give some more info. What is the problem exactly?

**Comment by CasperNaudts** [comment]
The power in and out entity just went inactive. Removing and adding the integration again didn't fix the issue.

**Comment by tijsverkoyen** [comment]
Seems to be working here. 
![image](https://github.com/joleys/niko-home-control-II/assets/250042/b825e0c2-9541-4ac4-adbc-235e8e2cbdb3)

I also upgraded to Home Assistant 2024.6.2 yesterday. And I upgraded the Niko Controller a few days ago.
But from what I see in the history it has kept working.

**Comment by CasperNaudts** [comment]
Seems that the latest version of the HA extension (4.3.2) fixed the issue for me.

**Comment by tijsverkoyen** [comment]
Ok, I'm going to close this issue.
